"""
Django settings for axf project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')o-3ow^^$7d*9iyy!ahae8d$rs@q6kogi5n0moaf30s13*ez(e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'mine',
    'order',
    'cart',
    'market',
    'home',
    'haystack',  # 全文检索框架，pip install django-haystack安装，引擎whoosh, pip install whoosh安装
    'rest_demo',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# mysql数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        "NAME":"axf_ex",
        "USER":"root",
        "PASSWORD":"456654",
        "HOST":"localhost",
        "PORT":"3306",

    }
}

# redis缓存配置
CACHES = {
    "default":{
        # 设定缓存到本地redis
        "BACKEND": "redis_cache.cache.RedisCache",
        # 缓存主机
        "LOCATION": "47.98.173.29:6379",
        # 缓存有效期
        "TIMEOUT": 3600,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# 语言配置
LANGUAGE_CODE = 'zh-Hans' # 'en-us'
# 地区时间配置
TIME_ZONE = "Asia/Shanghai"  # 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# 配置静态文件的路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# 配置头像上传路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置session使用redis
SESSION_ENGINE = "redis_sessions.session"
SESSION_REDIS_HOST = "47.98.173.29"
SESSION_REDIS_PORT = 6379
SESSION_REDIS_DB = 0
SESSION_REDIS_PASSWORD = ""
SESSION_REDIS_PREFIX = "session"

# session 设置过期时间
SESSION_COOKIE_AGE = 60 * 60 * 24 * 3  # 3天
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 关闭浏览器，则COOKIE不失效

# 设置django文件存储类
DEFAULT_FILE_STORAGE = 'fastdfs_demo.fdfs_storage.FdfsStorage'

# 设置fdfs存储服务器的ip以及端口号
FDFS_URL = 'http://47.98.173.29:8888/'

# 设置fdfs的client.conf文件路径
FDFS_CLIENT_CONF = './fastdfs_demo/client.conf'

# 添加搜索引擎
HAYSTACK_CONNECTIONS = {
    'default': {
        # 指定使用的搜索引擎
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # 指定索引文件存放位置
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}

#新增的数据自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# 分页输出值
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
