# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='book_query', to='rest_demo.Publish'),
        ),
    ]
