# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190126_0205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfomodel',
            table='axf_user_info',
        ),
    ]
