# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190126_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
